<a href="https://colab.research.google.com/github/VVdovichev/Linear_Algebra/blob/main/Lesson_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $$detA=sin^2(x)+cos^2(x)=1$$

In [ ]:
# б) 
det_A = 4 * 5 * 9
det_A

180

In [ ]:
# в)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $$det(A^{2})$$
    
   б) $$det(A^{T})$$
    
   в) $$det(2^nA)$$
  

а) $$A*A=16$$
б) $$A^{T}=4$$
в) $$2*A=8$$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [ ]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__4.__ Найти ранг матрицы:

   а) $$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$$

   б) $$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$$

In [ ]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица:\n{A}')
print(f'Матрица:\n{B}')
print(f'Ранг матрицы A: {np.linalg.matrix_rank(A)}')
print(f'Ранг матрицы B: {np.linalg.matrix_rank(B)}')

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы A: 2
Ранг матрицы B: 3
