<a href="https://colab.research.google.com/github/VVdovichev/Linear_Algebra/blob/main/Lesson_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np
import random

__1.__ Установить, какие произведения матриц AB и BA определены, и найти размерности полученных матриц:

   а) A — матрица 4 * 2, $B$ — матрица 4 * 2;
    
   б) A — матрица 2 * 5, B — матрица 5 * 3;
    
   в) A — матрица 8 * 3, B — матрица 3 * 8;
    
   г) A — квадратная матрица 4 * 4, B — квадратная матрица 4 * 4.

a) произведение матриц неопределено

б) произведение матриц определено, итоговая матрица имеет размерность 2×3

в) произведение матриц определено, итоговая матрица имеет размерность 8×8

г) произведение матриц определено, итоговая матрица имеет размерность 4×4

__2.__ Найти сумму и произведение матриц $$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$$ и $$B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$$

In [54]:
A = np.array([[1, -2] , [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'сумма матриц:\n{A + B}')
print(f'произведение матриц:\n{np.dot(A, B)}')

сумма матриц:
[[ 5 -3]
 [ 3  5]]
произведение матриц:
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию 3A-2B+4C для матриц $$A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$$, $$B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$$, $$C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$$

In [55]:
A = np.array([[1, 7] , [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
A_B_C = 3 * A - 2 * B + 4 * C
A_B_C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$$.
Вычислить $$AA^{T}$$ и $$A^{T}A$$.

In [56]:
A = np.array([[4, 1] , [5, -2], [2, 3]])
print(np.dot(A, A.T))
print(np.dot(A.T, A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [57]:
def matrixmult(m1,m2):
    s=0     #сумма
    t=[]    #временная матрица
    m3=[] # конечная матрица
    if len(m2)!=len(m1[0]):
        print("Матрицы не могут быть перемножены")        
    else:
        r1=len(m1) #количество строк в первой матрице
        c1=len(m1[0]) #Количество столбцов в 1   
        r2=c1           #и строк во 2ой матрице
        c2=len(m2[0])  # количество столбцов во 2ой матрице
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+m1[z][i]*m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]           
    return np.array(m3)
 
def creatematrix(r,c):
    t=[]
    m=[]
    for i in range(0,r):
        for j in range(0,c):
            t.append(random.randint(1,10))
        m.append(t)
        t=[]
    return np.array(m)
 
c1=1
r2=2
while c1!=r2:
    print("Кол-во столбцов в 1 матрице должно быть = кол-ву строк 2 матрицы")
    r1=int(input('Введите кол-во строк для 1 матрицы >'))
    c1=int(input('Введите кол-во столбцов для 1 матрицы>'))
    r2=int(input('Введите кол-во строк для второй матрицы >'))
    c2=int(input('Введите кол-во столбцов для 2 матрицы >'))
    
 
m1=creatematrix(r1,c1)
m2=creatematrix(r2,c2)
    
 
print("1я матрица \n", m1)
print('2я матрица \n', m2)
 
m3=matrixmult(m1,m2)
print("произведение матриц \n", m3)

Кол-во столбцов в 1 матрице должно быть = кол-ву строк 2 матрицы
Введите кол-во строк для 1 матрицы >4
Введите кол-во столбцов для 1 матрицы>3
Введите кол-во строк для второй матрицы >3
Введите кол-во столбцов для 2 матрицы >5
1я матрица 
 [[ 5  9  9]
 [ 1  7  6]
 [ 3  4  7]
 [ 4 10  1]]
2я матрица 
 [[ 7 10  3  3  7]
 [10  3  4  1  3]
 [ 2  1  4  2  5]]
произведение матриц 
 [[143  86  87  42 107]
 [ 89  37  55  22  58]
 [ 75  49  53  27  68]
 [130  71  56  24  63]]
