<a href="https://colab.research.google.com/github/VVdovichev/Linear_Algebra/blob/main/Lesson_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np

__1.__ Решить систему уравнений методом Крамера:

   а) $$\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$$
    
   б) $$\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$$


In [43]:
# a)


A = np.array([[1, -2], [3, -4]])
A1 = np.array([[1, -2], [7, -4]])
A2 = np.array([[1, 1], [3, 7]])
det_A = np.linalg.det(A)
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
x1 = det_A1 / det_A
x2 = det_A2 / det_A
print(f'x1 = {x1}')
print(f'x2 = {x2}')

x1 = 4.999999999999998
x2 = 1.9999999999999991


In [44]:
# б)


B = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
B1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
B2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
B3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
det_B = np.linalg.det(B)
det_B1 = np.linalg.det(B1)
det_B2 = np.linalg.det(B2)
det_B3 = np.linalg.det(B3)
x1 = det_B1 / det_B
x2 = det_B2 / det_B
x3 = det_B3 / det_B
print(f'x1 = {x1}')
print(f'x2 = {x2}')
print(f'x3 = {x3}')

x1 = 2.0000000000000018
x2 = -1.0000000000000009
x3 = 1.0


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а) $$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
Вычтем из 2й строки 1ю * 2

из 3й строки 1ю * 3
$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

$$l_{21}=2$$
$$l_{31}=3$$
из 3й строки вычтем 2ю * 4

$$l_{32}=4$$

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$


$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0\\ 
3 & 4 & 1
\end{pmatrix}$$




б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$



$$l_{21}=2$$
$$l_{31}=3$$
$$l_{41}=4$$


$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$


$$l_{32}=5$$
$$l_{42}=6$$


$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$


$$l_{43}=7$$


$$U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$


$$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [46]:
def LU(a, b):
    cout = 0
    m, n = a.shape
    if (m !=n ):
        print('Количество уравнений не равно количеству неизвестных.')
    else:
        l = np.zeros((n,n))
        u = np.zeros((n,n))
        s1 = 0
        s2 = 0

        for i in range(n):
           l[i][0] = a[i][0]
           u[i][i] = 1
        for j in range(1, n):
            u[0][j] = a[0][j] / l[0][0]
        for k in range(1, n):
            for i in range(k, n):
                for r in range(k): s1 += l[i][r] * u[r][k]
                l[i][k] = a[i][k] - s1
                s1 = 0                # Инициализировать s1 после каждого суммирования=0
            for j in range(k+1, n):
                for r in range(k): s2 += l[k][r] * u[r][j]
                u[k][j] = (a[k][j] - s2) / l[k][k]
                s2 = 0                # Инициализировать s2 после каждого суммирования=0
        print(u)
        print(l)

         #      
        y = np.zeros(n)
        s3 = 0
        y[0] = b[0] / l[0][0]    # Сначала вычисляем первое x решение
        for k in range(1, n):
            for r in range(k):
                s3 += l[k][r] * y[r]
            y[k] = (b[k]-s3) / l[k][k]
            s3 = 0

                 # Back Generation Solve
        x = np.zeros(n)
        s4 = 0
        x[n-1] = y[n-1]
        for k in range(n-2, -1, -1):
            for r in range(k+1, n):
                s4 += u[k][r] * x[r]
            x[k] = y[k] - s4
            s4 = 0

        for i in range(n):
               print("x" + str(i + 1) + " = ", x[i])
        print("x" " = ", x)

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [47]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])
LU(a, b)

[[ 1.          0.5         1.5       ]
 [ 0.          1.         -7.66666667]
 [ 0.          0.          1.        ]]
[[ 2.          0.          0.        ]
 [11.          1.5         0.        ]
 [ 9.          3.5        17.33333333]]
x1 =  -1.0
x2 =  0.0
x3 =  1.0
x =  [-1.  0.  1.]


__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [50]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
det_A = np.linalg.det(A)
w, v = np.linalg.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Определитель: {det_A}')
print(A == A.T)
w > 0

Собственные значения:
[134.72475295   4.55103023  29.72421681]
Определитель: 18225.000000000007
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([ True,  True,  True])

Все условия для решения методом Холецкого соблюдины, тогда произведем разложение на $$LL^{T}$$
$$l_{11}=\sqrt{a_{11}}=9$$
$$l_{21}=\frac{a_{21}}{l_{11}}=-5$$
$$l_{31}=\frac{a_{21}}{l_{11}}=5$$
$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - (-5)^{2}}=5$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=2$$
$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-5^{2}-2^{2}}=3$$
Получили
$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$
Решим систему $$Ly=b:$$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}==-33,$$

$$y_{3}=-12$$


$$L^{T}x=y:$$
$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=-5,$$

$$x_{1}=6.$$

In [51]:
print(np.linalg.cholesky(A))

[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]
