<a href="https://colab.research.google.com/github/VVdovichev/Linear_Algebra/blob/main/Lesson_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [5]:
A = np.array([[-1,-6], [2, 6]])
A

array([[-1, -6],
       [ 2,  6]])

In [6]:
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$Ae_{1}=-1\cdot e_{1}+0\cdot e_{2}=-e_{1}$$
$$Ae_{2}=0\cdot e_{1}-1\cdot e_{2}=-e_{2}$$


Теперь найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & 1\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(-1-\lambda)-0\cdot0=0,$$

$$(1+\lambda)^{2}=0,$$

$$\lambda=-1.$$
Теперь найдем собственные векторы вида $$\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$$ подставив полученное собственное значение в выражение $$\textbf{A}x=\lambda x$$

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$


Получим

$$\begin{cases}
-x_{1}= -x_{1}, \\
-x_{2}= -x_{2}.
\end{cases}$$ 

$$\begin{cases}
0=0, \\
0=0.
\end{cases}$$
следовательно любое
$$x_{1},x_{2}$$
удовлетворяют условиям системы уравнений.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $$x=(1,1)$$ собственным вектором этого линейного оператора.


In [7]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
print(f'Собственные числа: {w}')

Собственные числа: [2.00000002 1.99999998]


$$\begin{cases}
x_{1}+x_{2}= 2\cdot x_{1}, \\
-x_{1}+3\cdot x_{2}= 2\cdot x_{2}.
\end{cases}$$ 

$$\begin{cases}
x_{1}=x_{2}, \\
x_{1}=x_{2}.
\end{cases}$$ 

следовательно любое
$$x_{1}=x_{2}$$
удовлетворяют условиям системы уравнений и значит вектор $$x=(1,1)$$ является собственным.

**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $$x=(3, -3, -4)$$ собственным вектором этого линейного оператора.

Предположим, что вектор $$x$$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $$\lambda$$ при котором

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}.
$$
Из этого будет следовать, что
$$\begin{cases}
\lambda=-3\\
\lambda=-3\\
\lambda=3
\end{cases}$$ 

система решения не имеет, значит вектор $$x=(3, -3, -4)$$ не является собственным.